twitter-forks/presto

presto-hive/src/main/java/com/facebook/presto/hive/util/HiveFileIterator.java
This is equivalent to having no data for that partition. Simply ignore FileNotFoundException.
=> Ignore errors if the partitions have no corresponding valid hdfs path.

presto-hive/src/main/java/com/facebook/presto/hive/parquet/ParquetHiveRecordCursor.java
Parquet only calls converts for which it found the values. The missing
values are not reported. The BlockBuilder must be appended with
nulls for the missing values based on fieldIndex of the currently
read value by Parquet.
=> Append nulls for missing values in Parquet.

presto-hive/src/main/java/com/facebook/presto/hive/BackgroundHiveSplitLoader.java, presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java, presto-hive/src/main/java/com/facebook/presto/hive/util/UgiUtils.java
Previous patches changed BackgroundHiveSplitLoader to support read-as-user from HDFS on the coordinator. This patch changes HivePageSourceProvider to support read-as-user from HDFS on the workers.
=> HivePageSourceProvider to support query as user from workers

presto-hive/src/main/java/com/facebook/presto/hive/util/UgiUtils.java
Our last changed blocked zeppelin. A zeppelin patch is on it's way, but a few weeks out. Will revert this once that ships. Tracking in IQ-152.
=> Whitelist zeppelin temporarily

presto-main/src/main/java/com/facebook/presto/execution/SqlQueryManager.java
Adds logging of all queries executed, their end state, user and duration. We'd like to be able to post-process these logs and track the number of successful and failed queries over time. This could certainly be done more fancy with pluggable logging modules or a new query.log file, but this seems like a reasonable first pass.
Format (tab-delimited):
```QUERY_ID STATE ERROR_TYPE ERROR_CODE USER ELAPSED_TIME QUERY```
Executing this in the shell:
```
presto> set session
-> invalid.property.key='foo';
...
presto> show catalogs;
...
```
Produces this in ```server.log```:
```
2016-02-24T14:44:10.398-0800	INFO	query-execution-1	com.facebook.presto.execution.SqlQueryManager	Query complete	20160224_224410_00001_rjae5	FAILED	USER_ERROR	SYNTAX_ERROR:1	billg	594.74us	set session …
```
=> Add query logging of all presto queries

presto-hive/src/main/java/com/facebook/presto/hive/parquet/ParquetTypeUtils.java
Parquet schema is case sensitive but hive is not so camelCase parquet fields are not found when accessed as lowercase hive columns.
=> Look up parquet columns by name case-insensitive

pom.xml, presto-main/pom.xml, presto-main/src/main/java/com/facebook/presto/event/EventProcessor.java, presto-main/src/main/java/com/facebook/presto/event/query/QueryCompletionEvent.java, presto-main/src/main/java/com/facebook/presto/event/query/QueryCreatedEvent.java, presto-main/src/main/java/com/facebook/presto/event/query/QueryEvent.java, presto-main/src/main/java/com/facebook/presto/event/query/QueryEventHandler.java, presto-main/src/main/java/com/facebook/presto/event/query/SplitCompletionEvent.java, presto-main/src/main/java/com/facebook/presto/twitter/TwitterModuleLoader.java, presto-main/src/main/java/com/facebook/presto/twitter/logging/QueryLogger.java, presto-main/src/main/java/com/facebook/presto/twitter/logging/QueryScriber.java
Adding code to scribe log completion events along with a generic way to register event processors for QueryCreatedEvents, QueryCompletionEvents and SplitCompletionEvents. The parts not under the ```twitter```package  (and not the pom changes of course) could be contributed to OSS Presto. If not, those changes should move into the twitter-specific package.
=> Add event processer and handlers and scribe query completion events

pom.xml, presto-main/pom.xml
removed scala 2.11 dependencies from thrift-java; downgraded util-logging to 2.10
=> Fix scala dependency issues 

pom.xml, presto-hive/pom.xml, presto-hive/src/main/java/com/facebook/presto/hive/HiveClientModule.java, presto-hive/src/main/java/com/facebook/presto/twitter/hive/PooledHiveMetastoreClientFactory.java, presto-hive/src/main/java/com/facebook/presto/twitter/hive/ZookeeperServersetHiveCluster.java, presto-hive/src/main/java/com/facebook/presto/twitter/hive/ZookeeperServersetMetastoreConfig.java, presto-hive/src/main/java/com/facebook/presto/twitter/hive/util/PooledTTransportFactory.java, presto-hive/src/main/java/com/facebook/presto/twitter/hive/util/TTransportPool.java, presto-hive/src/test/java/com/facebook/presto/hive/TestingHiveCluster.java, presto-hive/src/test/java/com/facebook/presto/twitter/hive/TestZookeeperServersetMetastoreConfig.java
Even if we set the socket native "so_reuseaddr" flag to true, we still need to explicitly bind the local address. Therefore we have to have a port pool to record which ports are used for connecting hive metastore. This working prototype of pooling TTransport is proposed to avoid reallocate and reconnect socket.
The connection number end at 8 for each single metastore instance for 10 concurrent queries in "devel". It approximately uses the same runtime comparing without a connection pool. If this approach is favored, It can come with more settings for abandoning, idle connections and much more.
=> add connection pool

presto-hive/src/main/java/com/facebook/presto/hive/HiveWriteUtils.java
We can use this workaround to allow user create a table under the "default" schema.
=> Put the tmp path under a user's folder

presto-main/src/main/java/com/facebook/presto/server/StatementResource.java
Fix NPE in the unit test.
The NPE may be raised if the client doesn't set the request header "User-Agent", converting `null` to empty string can solve it.
=> NPE fix for test

presto-hive/src/main/java/com/facebook/presto/hive/BackgroundHiveSplitLoader.java
It appears that some lzo index files might be incorrect/corrupt(index runover file end). To help data vendor to re-index the file/drop the index file, Presto could include the file path in the error message.
=> Added file path for errors on splitting blocks

presto-hive/src/main/java/com/facebook/presto/twitter/hive/thrift/ThriftHiveRecordCursor.java
Fix the thrift reader row/map block builder issue
```
SELECT * FROM datapipeline.logs_mediaservices_media_upload LIMIT 2;
ava.lang.UnsupportedOperationException: com.facebook.presto.spi.block.RowBlockBuilder
at com.facebook.presto.spi.block.BlockBuilder.writeBytes(BlockBuilder.java:58)
at com.facebook.presto.spi.type.VarcharType.writeSlice(VarcharType.java:166)
at com.facebook.presto.spi.type.VarcharType.writeSlice(VarcharType.java:160)
at com.facebook.presto.twitter.hive.thrift.ThriftHiveRecordCursor.serializePrimitive(ThriftHiveRecordCursor.java:691)
at com.facebook.presto.twitter.hive.thrift.ThriftHiveRecordCursor.serializeObject(ThriftHiveRecordCursor.java:553)
at com.facebook.presto.twitter.hive.thrift.ThriftHiveRecordCursor.serializeStruct(ThriftHiveRecordCursor.java:650)
at …
```
=> Fix row/map block builder for hive thrift reader

presto-hive/src/main/java/com/facebook/presto/hive/HiveWriteUtils.java
A newer version of the shaded Hadoop lib used for Presto is wrapping the raw file system under FileSystemWrapper which caused Presto missed our HDFSCompatibleViewFileSystem check.
`hdfsEnvironment.getFileSystem(context, targetPath).getClass().getName()` is `org.apache.hadoop.fs.PrestoFileSystemCache$FileSystemWrapper`
=> Unwrap the FileSystemWrapper in isHDFSCompatibleViewFileSystem

presto-main/src/main/java/com/facebook/presto/type/RowParametricType.java, presto-spi/src/main/java/com/facebook/presto/spi/type/TypeSignature.java, presto-spi/src/test/java/com/facebook/presto/spi/type/TestTypeSignature.java
Problem:
```
java.lang.NullPointerException: type is null
at com.facebook.presto.spi.ColumnMetadata.<init>(ColumnMetadata.java:46)
at com.facebook.presto.hive.HiveMetadata.lambda$columnMetadataGetter$14(HiveMetadata.java:1407)
at com.facebook.presto.hive.HiveMetadata.getTableMetadata(HiveMetadata.java:250)
at com.facebook.presto.hive.HiveMetadata.getTableMetadata(HiveMetadata.java:237)
at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.getTableMetadata(ClassLoaderSafeConnectorMetadata.java:127)
at com.facebook.presto.metadata.MetadataManager.getTableMetadata(MetadataManager.java:337)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:756)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(Stat …
```
=> Automatically insert an unknown type for empty structural type

pom.xml, presto-twitter-functions/pom.xml, presto-twitter-functions/src/main/java/com/facebook/presto/twitter/functions/TwitterFunctionsPlugin.java, presto-twitter-functions/src/main/java/com/facebook/presto/twitter/functions/TwitterStringFunctions.java, presto-twitter-functions/src/test/java/com/facebook/presto/twitter/functions/TestTwitterFunctions.java, presto-twitter-server/src/main/provisio/twitter.xml
split_every(string) → array<varchar>
Splits `string` on every character and returns an array.
split_every(string, length) → array<varchar>
Splits `string` on every `length` characters and returns an array. `length` must be a positive number.
split_every(string, length, limit) → array<varchar>
Splits `string` on every `length` characters and returns an array of size at most `limit`. The last element in the array always contains everything left in the string. `limit` must be a positive number.
=> Add split_every function

presto-main/src/main/java/com/facebook/presto/server/security/AuthenticationFilter.java, presto-main/src/main/java/com/facebook/presto/server/security/SecurityConfig.java, presto-main/src/main/java/com/facebook/presto/server/security/ServerSecurityModule.java, presto-main/src/test/java/com/facebook/presto/server/security/TestSecurityConfig.java
This is useful when the non-secured port hosted behind a secured front-end service and direct non-secured port access has been limited by a firewall
=> Allow non-secured request authentication over pathes matching given regrex

presto-client/src/main/java/com/facebook/presto/client/SpnegoHandler.java, presto-main/src/main/java/com/facebook/presto/server/security/KerberosAuthenticator.java, presto-product-tests/conf/presto/etc/singlenode-kerberized.properties, presto-product-tests/conf/tempto/tempto-configuration-for-docker-kerberos.yaml
The built-in host-based service name type for Kerberos authenticator cannot fit our use case. By allowing pass a specific service principle and use the user based name type, the authenticator can be authenticated by Kerberos master without specifying the host running Presto service.
This should be a common scenario that the service is running on a managed cloud computing environment.
=> Allow specifying service principal for Kerberos authenticator

presto-hive/src/main/java/com/facebook/presto/hive/parquet/HadoopLzoDecompressor.java, presto-hive/src/main/java/com/facebook/presto/hive/parquet/ParquetCompressionUtils.java
Use HadoopLzoDecompressor in ParquetCompressionUtils. The HadoopLzoDecompressor implements the airlift Decompressor interface and replaces the aircompressor LzoDecompressor in decompressLZO function.
=> Use HadoopLzoDecompressor in ParquetCompressionUtils

presto-hive/src/main/java/com/facebook/presto/hive/parquet/ParquetPageSource.java, presto-hive/src/main/java/com/facebook/presto/hive/parquet/ParquetTypeUtils.java
Fix the issue where optimized parquet reader can't find field when the filed name differs from that in parquet file metadata.
=> Fix find field by name in optimized parquet reader

presto-docs/src/main/sphinx/functions.rst, presto-docs/src/main/sphinx/functions/twitter.rst, presto-twitter-functions/src/main/java/com/facebook/presto/twitter/functions/SnowflakeFunctions.java, presto-twitter-functions/src/main/java/com/facebook/presto/twitter/functions/TwitterFunctionsPlugin.java, presto-twitter-functions/src/test/java/com/facebook/presto/twitter/functions/TestTwitterFunctions.java
Add utility functions for snowflake id.
https://developer.twitter.com/en/docs/basics/twitter-ids
```
is_snowflake(id) → boolean
Return if a bigint is a snowflake ID (true/false).
first_snowflake_for(timestamp) → bigint
Return the first snowflake ID given a timestamp.
timestamp_from_snowflake(id) → timestamp
Return the timestamp given a snowflake ID.
cluster_id_from_snowflake(id) → bigint
Return the cluster ID given a snowflake ID.
instance_id_from_snowflake(id) → bigint
Return the instance ID given a snowflake ID.
sequence_num_from_snowflake(id) → bigint
Return the sequence number given a snowflake ID.
```
=> Add Snowflake functions

presto-main/src/main/java/com/facebook/presto/execution/resourceGroups/InternalResourceGroup.java
This fixes #10383, where deployments using the legacy resource group
configuration manager were unable to run more than a single query that
used memory concurrently.
=> Set default soft memory limit to Long.MAX_VALUE

twitter-eventlistener-plugin/src/main/java/com/twitter/presto/plugin/eventlistener/QueryCompletedEventScriber.java
In `twitter-eventlistener-plugin`, thriftEvent is not using setter function to add fields, which leaves the `__isset_bit_vector` bit in thrift object unset. Therefore, all optional fields are thrown away in serialization.
=> Fix missing fields in thriftEvent in eventlistener
